/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-11-14.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The CampaignCloneQueryAsSubResourceAttributes model module.
 * @module model/CampaignCloneQueryAsSubResourceAttributes
 * @version 2022-11-14.pre
 */
export class CampaignCloneQueryAsSubResourceAttributes {
  /**
   * Constructs a new <code>CampaignCloneQueryAsSubResourceAttributes</code>.
   * @alias module:model/CampaignCloneQueryAsSubResourceAttributes
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CampaignCloneQueryAsSubResourceAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CampaignCloneQueryAsSubResourceAttributes} obj Optional instance to populate.
   * @return {module:model/CampaignCloneQueryAsSubResourceAttributes} The populated <code>CampaignCloneQueryAsSubResourceAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CampaignCloneQueryAsSubResourceAttributes();
      if (data.hasOwnProperty('new_name'))
        obj.newName = ApiClient.convertToType(data['new_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} newName
 */
CampaignCloneQueryAsSubResourceAttributes.prototype.newName = undefined;

