/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-11-14.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The ContentSubObject model module.
 * @module model/ContentSubObject
 * @version 2022-11-14.pre
 */
export class ContentSubObject {
  /**
   * Constructs a new <code>ContentSubObject</code>.
   * @alias module:model/ContentSubObject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContentSubObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentSubObject} obj Optional instance to populate.
   * @return {module:model/ContentSubObject} The populated <code>ContentSubObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContentSubObject();
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('preview_text'))
        obj.previewText = ApiClient.convertToType(data['preview_text'], 'String');
      if (data.hasOwnProperty('from_email'))
        obj.fromEmail = ApiClient.convertToType(data['from_email'], 'String');
      if (data.hasOwnProperty('from_label'))
        obj.fromLabel = ApiClient.convertToType(data['from_label'], 'String');
      if (data.hasOwnProperty('template_id'))
        obj.templateId = ApiClient.convertToType(data['template_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} subject
 */
ContentSubObject.prototype.subject = undefined;

/**
 * @member {String} previewText
 */
ContentSubObject.prototype.previewText = undefined;

/**
 * @member {String} fromEmail
 */
ContentSubObject.prototype.fromEmail = undefined;

/**
 * @member {String} fromLabel
 */
ContentSubObject.prototype.fromLabel = undefined;

/**
 * @member {String} templateId
 */
ContentSubObject.prototype.templateId = undefined;

