/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-09-07.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {IncludedFlowAttributes} from './IncludedFlowAttributes.js';
import {IncludedVariantsLinks} from './IncludedVariantsLinks.js';

/**
 * The IncludedFlow model module.
 * @module model/IncludedFlow
 * @version 2022-09-07.pre
 */
export class IncludedFlow {
  /**
   * Constructs a new <code>IncludedFlow</code>.
   * @alias module:model/IncludedFlow
   * @class
   * @param type {module:model/IncludedFlow.TypeEnum} 
   * @param id {String} 
   * @param attributes {module:model/IncludedFlowAttributes} 
   * @param links {module:model/IncludedVariantsLinks} 
   */
  constructor(type, id, attributes, links) {
    this.type = type;
    this.id = id;
    this.attributes = attributes;
    this.links = links;
  }

  /**
   * Constructs a <code>IncludedFlow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludedFlow} obj Optional instance to populate.
   * @return {module:model/IncludedFlow} The populated <code>IncludedFlow</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludedFlow();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = IncludedFlowAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('links'))
        obj.links = IncludedVariantsLinks.constructFromObject(data['links']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
IncludedFlow.TypeEnum = {
  /**
   * value: "flow"
   * @const
   */
  flow: "flow"
};
/**
 * @member {module:model/IncludedFlow.TypeEnum} type
 */
IncludedFlow.prototype.type = undefined;

/**
 * @member {String} id
 */
IncludedFlow.prototype.id = undefined;

/**
 * @member {module:model/IncludedFlowAttributes} attributes
 */
IncludedFlow.prototype.attributes = undefined;

/**
 * @member {module:model/IncludedVariantsLinks} links
 */
IncludedFlow.prototype.links = undefined;

