/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-12-15.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {IncludedProfileAttributes} from './IncludedProfileAttributes.js';
import {IncludedTagsLinks} from './IncludedTagsLinks.js';

/**
 * The IncludedProfile model module.
 * @module model/IncludedProfile
 * @version 2022-12-15.pre
 */
export class IncludedProfile {
  /**
   * Constructs a new <code>IncludedProfile</code>.
   * @alias module:model/IncludedProfile
   * @class
   * @param type {module:model/IncludedProfile.TypeEnum} 
   * @param id {String} 
   * @param attributes {module:model/IncludedProfileAttributes} 
   * @param links {module:model/IncludedTagsLinks} 
   */
  constructor(type, id, attributes, links) {
    this.type = type;
    this.id = id;
    this.attributes = attributes;
    this.links = links;
  }

  /**
   * Constructs a <code>IncludedProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludedProfile} obj Optional instance to populate.
   * @return {module:model/IncludedProfile} The populated <code>IncludedProfile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludedProfile();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = IncludedProfileAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('links'))
        obj.links = IncludedTagsLinks.constructFromObject(data['links']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
IncludedProfile.TypeEnum = {
  /**
   * value: "profile"
   * @const
   */
  profile: "profile"
};
/**
 * @member {module:model/IncludedProfile.TypeEnum} type
 */
IncludedProfile.prototype.type = undefined;

/**
 * @member {String} id
 */
IncludedProfile.prototype.id = undefined;

/**
 * @member {module:model/IncludedProfileAttributes} attributes
 */
IncludedProfile.prototype.attributes = undefined;

/**
 * @member {module:model/IncludedTagsLinks} links
 */
IncludedProfile.prototype.links = undefined;

