/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-12-15.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The IncludedTagsLinks model module.
 * @module model/IncludedTagsLinks
 * @version 2022-12-15.pre
 */
export class IncludedTagsLinks {
  /**
   * Constructs a new <code>IncludedTagsLinks</code>.
   * @alias module:model/IncludedTagsLinks
   * @class
   * @param self {String} 
   */
  constructor(self) {
    this.self = self;
  }

  /**
   * Constructs a <code>IncludedTagsLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludedTagsLinks} obj Optional instance to populate.
   * @return {module:model/IncludedTagsLinks} The populated <code>IncludedTagsLinks</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludedTagsLinks();
      if (data.hasOwnProperty('self'))
        obj.self = ApiClient.convertToType(data['self'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} self
 */
IncludedTagsLinks.prototype.self = undefined;

