/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-09-07.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The IncludedFlowAttributes model module.
 * @module model/IncludedFlowAttributes
 * @version 2022-09-07.pre
 */
export class IncludedFlowAttributes {
  /**
   * Constructs a new <code>IncludedFlowAttributes</code>.
   * @alias module:model/IncludedFlowAttributes
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncludedFlowAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludedFlowAttributes} obj Optional instance to populate.
   * @return {module:model/IncludedFlowAttributes} The populated <code>IncludedFlowAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludedFlowAttributes();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('archived'))
        obj.archived = ApiClient.convertToType(data['archived'], 'Boolean');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('trigger_type'))
        obj.triggerType = ApiClient.convertToType(data['trigger_type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IncludedFlowAttributes.prototype.name = undefined;

/**
 * @member {String} status
 */
IncludedFlowAttributes.prototype.status = undefined;

/**
 * @member {Boolean} archived
 */
IncludedFlowAttributes.prototype.archived = undefined;

/**
 * @member {Date} created
 */
IncludedFlowAttributes.prototype.created = undefined;

/**
 * @member {Date} updated
 */
IncludedFlowAttributes.prototype.updated = undefined;

/**
 * @member {String} triggerType
 */
IncludedFlowAttributes.prototype.triggerType = undefined;

