/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-12-15.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The TemplateCloneQueryAsSubResource model module.
 * @module model/TemplateCloneQueryAsSubResource
 * @version 2022-12-15.pre
 */
export class TemplateCloneQueryAsSubResource {
  /**
   * Constructs a new <code>TemplateCloneQueryAsSubResource</code>.
   * @alias module:model/TemplateCloneQueryAsSubResource
   * @class
   * @param id {Object} The ID of MessageTemplate
   */
  constructor(id) {
    this.id = id;
  }

  /**
   * Constructs a <code>TemplateCloneQueryAsSubResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplateCloneQueryAsSubResource} obj Optional instance to populate.
   * @return {module:model/TemplateCloneQueryAsSubResource} The populated <code>TemplateCloneQueryAsSubResource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TemplateCloneQueryAsSubResource();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], Object);
    }
    return obj;
  }
}

/**
 * The ID of MessageTemplate
 * @member {Object} id
 */
TemplateCloneQueryAsSubResource.prototype.id = undefined;

