/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-09-07.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The TemplateRenderQueryAsSubResourceAttributes model module.
 * @module model/TemplateRenderQueryAsSubResourceAttributes
 * @version 2022-09-07.pre
 */
export class TemplateRenderQueryAsSubResourceAttributes {
  /**
   * Constructs a new <code>TemplateRenderQueryAsSubResourceAttributes</code>.
   * @alias module:model/TemplateRenderQueryAsSubResourceAttributes
   * @class
   * @param context {String} 
   */
  constructor(context) {
    this.context = context;
  }

  /**
   * Constructs a <code>TemplateRenderQueryAsSubResourceAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplateRenderQueryAsSubResourceAttributes} obj Optional instance to populate.
   * @return {module:model/TemplateRenderQueryAsSubResourceAttributes} The populated <code>TemplateRenderQueryAsSubResourceAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TemplateRenderQueryAsSubResourceAttributes();
      if (data.hasOwnProperty('context'))
        obj.context = ApiClient.convertToType(data['context'], 'String');
      if (data.hasOwnProperty('return_fields'))
        obj.returnFields = ApiClient.convertToType(data['return_fields'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} context
 */
TemplateRenderQueryAsSubResourceAttributes.prototype.context = undefined;

/**
 * @member {Array.<String>} returnFields
 */
TemplateRenderQueryAsSubResourceAttributes.prototype.returnFields = undefined;

