/*
 * Klaviyo API (Beta)
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-11-14.pre
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The UTMParamsSubObject model module.
 * @module model/UTMParamsSubObject
 * @version 2022-11-14.pre
 */
export class UTMParamsSubObject {
  /**
   * Constructs a new <code>UTMParamsSubObject</code>.
   * @alias module:model/UTMParamsSubObject
   * @class
   * @param name {String} 
   * @param value {String} 
   */
  constructor(name, value) {
    this.name = name;
    this.value = value;
  }

  /**
   * Constructs a <code>UTMParamsSubObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UTMParamsSubObject} obj Optional instance to populate.
   * @return {module:model/UTMParamsSubObject} The populated <code>UTMParamsSubObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UTMParamsSubObject();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
UTMParamsSubObject.prototype.name = undefined;

/**
 * @member {String} value
 */
UTMParamsSubObject.prototype.value = undefined;

